# Generated by Django 4.2.7 on 2023-11-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
