# Generated by Django 4.2.7 on 2023-11-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
